import os from 'node:os'
import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'

import cheerio from 'cheerio'
import fetch from 'node-fetch'

import { sleep } from './common.mjs'

const getIPv4Regex = () => new RegExp('\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}', 'gi')

const isIPv4 = (text) => getIPv4Regex().test(text)

const isWin = os.platform() === 'win32'
const isApple = os.platform() === 'darwin'

console.info('isWin: ', isWin)
console.info('isApple: ', isApple)

const domains = [
  'github.io',
  // 'github.com',

  'api.github.com',
  'gist.github.com',
  'central.github.com',
  'assets-cdn.github.com',
  'codeload.github.com',

  'github-com.s3.amazonaws.com',
  'github-cloud.s3.amazonaws.com',

  'raw.githubusercontent.com',
  'camo.githubusercontent.com',
  'desktop.githubusercontent.com',
  'favicons.githubusercontent.com',
  'avatars5.githubusercontent.com',
  'avatars4.githubusercontent.com',
  'avatars3.githubusercontent.com',
  'avatars2.githubusercontent.com',
  'avatars1.githubusercontent.com',
  'avatars0.githubusercontent.com',
  'avatars.githubusercontent.com',
  'user-images.githubusercontent.com',

  'github.map.fastly.net',
  'github.githubassets.com',
  'github.global.ssl.fastly.net',
]

async function getDomainIP(url) {
  const text = await fetch(`https://ipaddress.com/website/${url}`).then((res) => res.text())
  const $ = cheerio.load(text)
  const items = $('.panel tbody tr')
  let IPs = []
  let ip = ''
  items.each(function () {
    const node1 = $(this).find('th')
    const node2 = $(this).find('td')
    if (node1.text().includes('IP Address')) {
      ip = node2.text()
      if (isIPv4(ip)) IPs.push(ip)
    }
  })
  // 多个ip地址
  if (ip.includes('IPv4')) {
    items.each(function () {
      const node = $(this).find('td')
      const text = node.text()
      const match = text.match(getIPv4Regex())
      if (Array.isArray(match) && match.length) IPs.push(...match)
    })
  }
  return IPs
}

async function start() {
  const hosts = []
  for (const domain of domains) {
    console.info(`Start Get Domain ${domain}'s IP`)
    const IPs = await getDomainIP(domain)
    console.info(`Got Domain ${domain}'s IP`)
    if (Array.isArray(IPs)) {
      hosts.push(...IPs.map((ip) => `${ip.trim()} ${domain}`))
    }
    await sleep(5000)
  }
  return hosts
}

async function getGithubHosts() {
  const text = await fetch('https://gitee.com/fliu2476/github-hosts/raw/main/hosts').then((res) => res.text())
  console.info(text)
  return text
}

const getHostPath = () => {
  if (isWin) return 'C:\\Windows\\System32\\drivers\\etc\\hosts'
  if (isApple) return '/etc/hosts'
  return '/etc/hosts'
}

const getRefreshDnsCommand = () => {
  if (isWin) return 'ipconfig /flushdns'
  if (isApple) return 'killall -HUP mDNSResponder'
  return ''
}

const updateHosts = (hosts) => {
  const start = '# Generated by hosts-generator start'
  // const start = '# gitlab start'
  const end = '# Generated by hosts-generator end'
  // const end = '# gitlab end'

  const hostPath = getHostPath()
  const hostText = readFileSync(hostPath, { encoding: 'utf8' })

  const hostList = hostText.split('\r\n')
  const fromIdx = hostList.indexOf(start)
  const toIdx = hostList.indexOf(end)

  // if (fromIdx === -1 && toIdx === -1) hostList.push(start, ...hosts, end)
  // else hostList.splice(fromIdx + 1, toIdx - fromIdx - 1, ...hosts)
  if (fromIdx === -1 && toIdx === -1) hostList.push(start, hosts, end)
  else hostList.splice(fromIdx + 1, toIdx - fromIdx - 1, hosts)

  writeFileSync(hostPath, hostList.join('\r\n'), { encoding: 'utf8' })
  execSync(getRefreshDnsCommand())
  console.info('Refresh over')
}

getGithubHosts().then(updateHosts)
// start().then(updateHosts)
